services:
  app:
    image: sakuuj/simple_webapp
    container_name: simple_webapp
    build:
      dockerfile: ./Dockerfile
      target: production
    depends_on: 
      - postgres
    ports:
      - 127.0.0.1:80:8080
    networks:
      - webnet

  postgres:
    image: sakuuj/postgres_db_simple_webapp
    container_name: postgres_db_simple_webapp
    build: ./db
    networks:
      - webnet
    volumes:
      - pg_data:/var/lib/postgresql/data


networks:
  webnet:

volumes:
  pg_data:
